version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/go/src/app
    ports:
      - 1323:1323
    networks:
      - dockerdb_default
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB: graphQL
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root

networks:
    dockerdb_default:
        external: true
    